---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at <https://ds202-at-isu.github.io/labs.html> for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.

All submissions to the github repo will be automatically uploaded for grading once the due date is passed. Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

This is Nadia's line from RStudio.

Megan: This is a line from RStudio

Gwen: This is a line from RStudio.

**12.2**

The repo was already made!

**12.3**

Gwen: I had no problems cloning the GitHub repository to my computer via RStudio, creating the project went smoothly

Megan: I didn't have problems cloning the repo, but I did have to set up my git config --global.

**12.4**

Gwen: This step went smoothly as well. Talking with my group about the difference between commit and push, helped me to understand what was actually going on.

Megan: I was able to run git add and git commit without issues.

**12.5**

Gwen: I was able to push successfully the first time. Group members struggled with pulling and pushing their changes in this step and it we tried our best to talk through it with each other and tried different things.

Megan: I was able to push after pulling changes other team members had made. We set up an email chain so that we could coordinate when to make changes, so that we weren't all doing it at the same time.

**12.6**

Gwen: The changes were successfully updated, however when I tried to pull from the changes the group members have made I had pulling and merging issues and it took awhile to figure out how to fix. Hopefully all group members have no more issues!

Megan: Changes were successfully updated on the main branch since I pushed directly to main. We worked through some other group issues and asked questions when we ran into issues.

**Our Groups Experience**

-   We were struggling with the push process and some group members were struggling with errors and personal access tokens.
-   Megan (me) had to configure git, by installing the package, running git config user.name and user.email and generating a token (PAT). Then I pulled and resolve merge conflicts, made a commit with my text, and then I was able to push to main.
